[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=optional --ignore-scripts"]

[phases.build]
cmds = ["npm run build && mkdir -p .next/standalone/.next && cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/"]

[start]
cmd = "node .next/standalone/server.js"
