[build]
builder = "nixpacks"
buildCommand = "npm install --omit=optional --ignore-scripts && npm run build"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/api/system-status"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
